### Create a 2D `NumPy` Array

In [1]:
import numpy as np

<p>Consider the list <code>a</code>, which contains three nested lists <b>each of equal size</b>.</p>

In [2]:
a = [[10, 11, 12], [20, 21, 22], [30, 31, 32]]
a

[[10, 11, 12], [20, 21, 22], [30, 31, 32]]

<p>We can cast the list to a Numpy Array as follows:</p>

In [3]:
npa = np.array(a)
npa

array([[10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

<p>We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions, referred to as the rank.</p>

In [4]:
npa.ndim

2

<p>Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.</p>

In [5]:
npa.shape

(3, 3)

<p>The total number of elements in the array is given by the attribute <code>size</code>.</p>

In [6]:
npa.size

9

### Accessing different elements of a `NumPy` Array

<p>We simply use the square brackets and the indices corresponding to the element we would like:</p>

In [7]:
npa[1, 2]

np.int64(22)

<p>We can also use the following notation to obtain the elements:</p>

In [8]:
npa[1][2]

np.int64(22)

<p>We can also use slicing in numpy arrays.</p>

<p>We would like to obtain the first two columns in the first row. This can be done with the following syntax.</p>

In [9]:
# Access the element on the first row and first and second columns
npa[0][0: 2]

array([10, 11])

<p>Similarly, we can obtain the first two rows of the 3rd column as follows:</p>

In [10]:
npa[0: 2, 2]

array([12, 22])

### Basic Operations

<p>We can also add arrays. The process is identical to matrix addition. Matrix addition of <code>x</code> and <code>y</code> is shown in the following figure:</p>

<div style="display: flex; align-items: flex-end; gap: 20px; margin: 20px 0;">
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold; ">x</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
                <td style="padding: 8px 12px; border: 1px solid;">0</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">0</td>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
            </tr>
        </table>
    </div>
    <span style="font-size: 24px;  margin-bottom: 24px;">+</span>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">y</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">2</td>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
                <td style="padding: 8px 12px; border: 1px solid;">2</td>
            </tr>
        </table>
    </div>
    <span style="font-size: 24px;  margin-bottom: 24px;">=</span>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">x+y (Process)</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1+2</td>
                <td style="padding: 8px 12px; border: 1px solid;">0+1</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">0+1</td>
                <td style="padding: 8px 12px; border: 1px solid;">1+2</td>
            </tr>
        </table>
    </div>
    <span style="font-size: 24px;  margin-bottom: 24px;">=</span>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">x+y (Result)</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">3</td>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">1</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">1</td>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">3</td>
            </tr>
        </table>
    </div>
</div>

<p>The numpy array is given by <code>x</code> and <code>y</code>.</p>

In [11]:
x = np.array([[1, 0], [0, 1]])
x

array([[1, 0],
       [0, 1]])

In [12]:
y = np.array([[2, 1], [1, 2]])
y

array([[2, 1],
       [1, 2]])

<p>We can add the numpy arrays as follows.</p>

In [13]:
x + y

array([[3, 1],
       [1, 3]])

<p>Multiplying a numpy array by a scaler is identical to multiplying a matrix by a scaler. If we multiply the matrix <code>y</code> by the scaler 2, we simply multiply every element in the matrix by 2, as shown in the figure.</p>

<div style="display: flex; flex-direction: column; gap: 30px; margin: 20px 0;">
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">y</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">2</td>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
                <td style="padding: 8px 12px; border: 1px solid;">2</td>
            </tr>
        </table>
    </div>
    <div style="display: flex; align-items: center; gap: 20px; justify-content: center;">
        <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
            <span style="font-size: 16px; font-weight: bold;">2y</span>
            <table style="border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px 12px; border: 1px solid;">2×2</td>
                    <td style="padding: 8px 12px; border: 1px solid;">2×1</td>
                </tr>
                <tr>
                    <td style="padding: 8px 12px; border: 1px solid;">2×1</td>
                    <td style="padding: 8px 12px; border: 1px solid;">2×2</td>
                </tr>
            </table>
        </div>
        <span style="font-size: 24px;">=</span>
        <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
            <span style="font-size: 16px; font-weight: bold;">Result</span>
            <table style="border-collapse: collapse;">
                <tr>
                    <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">4</td>
                    <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">2</td>
                </tr>
                <tr>
                    <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">2</td>
                    <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">4</td>
                </tr>
            </table>
        </div>
    </div>
</div>


<p>We can perform the same operation in numpy as follows.</p>

In [14]:
2 * y

array([[4, 2],
       [2, 4]])

<p>Multiplication of two arrays corresponds to an element-wise product or <em>Hadamard product</em>. Consider matrix <code>X</code> and <code>Y</code>. The Hadamard product corresponds to multiplying each of the elements in the same position, i.e. multiplying elements contained in the same color boxes together. The result is a new matrix that is the same size as matrix <code>Y</code> or <code>X</code>, as shown in the following figure.</p>

<div style="display: flex; align-items: flex-end; gap: 20px; margin: 20px 0;">
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold; ">x</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
                <td style="padding: 8px 12px; border: 1px solid;">0</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">0</td>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
            </tr>
        </table>
    </div>
    <span style="font-size: 24px; margin-bottom: 24px;">×</span>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">y</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">2</td>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1</td>
                <td style="padding: 8px 12px; border: 1px solid;">2</td>
            </tr>
        </table>
    </div>
    <span style="font-size: 24px; margin-bottom: 24px;">=</span>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">x×y (Process)</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">1×2</td>
                <td style="padding: 8px 12px; border: 1px solid;">0×1</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; border: 1px solid;">0×1</td>
                <td style="padding: 8px 12px; border: 1px solid;">1×2</td>
            </tr>
        </table>
    </div>
    <span style="font-size: 24px; margin-bottom: 24px;">=</span>
    <div style="display: flex; flex-direction: column; align-items: center; gap: 8px;">
        <span style="font-size: 16px; font-weight: bold;">x×y (Result)</span>
        <table style="border-collapse: collapse;">
            <tr>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">2</td>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">0</td>
            </tr>
            <tr>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">0</td>
                <td style="padding: 8px 12px; font-weight: bold; border: 1px solid;">2</td>
            </tr>
        </table>
    </div>
</div>

<p>We can perform element-wise product of the array <code>x</code> and <code>y</code> as follows:</p>

In [15]:
x * y

array([[2, 0],
       [0, 2]])

<p>We can also perform matrix multiplication with the numpy arrays <code>a</code> and <code>b</code> as follows:</p>

<p>First, we define matrix <code>a</code> and <code>b</code>:</p>

In [16]:
a = np.array([[0, 1, 3], [2, 0, 3]])
a

array([[0, 1, 3],
       [2, 0, 3]])

In [17]:
b = np.array([[0, 2], [9, 9], [-1, 2]])
b

array([[ 0,  2],
       [ 9,  9],
       [-1,  2]])

<p>We use the numpy function <code>dot</code> to multiply the arrays together.</p>

In [18]:
c = np.dot(a, b)
c

array([[ 6, 15],
       [-3, 10]])

In [19]:
np.sin(c)

array([[-0.2794155 ,  0.65028784],
       [-0.14112001, -0.54402111]])

<p>We use the numpy attribute <code>T</code> to calculate the transposed matrix.</p>

In [20]:
c = np.array([[1, 2], [3, 4], [5, 6]])
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
c.T

array([[1, 3, 5],
       [2, 4, 6]])

### Quiz on 2D `NumPy` Array

<p>Consider the following list <code>a</code>, convert it to Numpy Array.</p>

In [22]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
npa = np.array(a)
npa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

<p>Calculate the numpy array size.</p>

In [23]:
npa.size

12

<p>Access the element on the first row and first and second columns.</p>

In [24]:
npa[0, 0: 2]

array([1, 2])

<p>Perform matrix multiplication with the numpy arrays <code>npa</code> and <code>npb</code>.</p>

In [25]:
npb = np.array([[0, 1], [2, 3], [-2, 0], [1, 1]])
npb

array([[ 0,  1],
       [ 2,  3],
       [-2,  0],
       [ 1,  1]])

In [26]:
np.dot(npa, npb)

array([[ 2, 11],
       [ 6, 31],
       [10, 51]])

****
This is the end of the file.
****